version: '3'

services:
  web:
    # build:
    #   context: ./
    #   dockerfile: ./Dockerfile
    image: nginx:stable-alpine
    container_name: admin-pro
    privileged: true
    restart: always
    ports:
      - '80:80'
    volumes:
      - ../dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    command: [nginx-debug, '-g', 'daemon off;']

volumes:
  dist:
